FROM ubuntu:latest


# Set user and temporary home directory for package installations
USER root


# Set the working directory inside the container
WORKDIR /app


# Install Java (using default to avoid "no installation candidate" errors)
RUN apt-get update && \
    apt-get install -y python3 python3-pip libc-bin --no-install-recommends default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Dynamically set JAVA_HOME 
# This command finds the actual install path and sets it as an environment variable
RUN export JAVA_PATH=$(readlink -f /usr/bin/java | sed "s:/bin/java::") && \
    echo "export JAVA_HOME=$JAVA_PATH" >> /etc/environment


# Setting it for the Docker build environment
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="$JAVA_HOME/bin:${PATH}"


# Set environment variables for Spark with Delta Lake
ARG DELTA_FULL_VERSION=delta-spark_2.13:4.0.1
ENV PYSPARK_SUBMIT_ARGS="--packages io.delta:${DELTA_FULL_VERSION} --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog pyspark-shell"


# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt


# Copy the startup script
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh


# Define the command to run the startup script
CMD ["/app/start.sh"]
