version: "3.9"

x-spark-base: &spark-base
  build:
    context: ./
    dockerfile: Dockerfile-spark
  tmpfs:
    - /tmp/spark-events
    - /opt/spark/work-dir/cache:size=1G
  environment:
    - SPARK_NO_DAEMONIZE=true
    - SPARK_CONF_DIR=/opt/spark/conf
    - _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true

services:

  spark-master:
    <<: *spark-base
    container_name: spark-master
    ports: ["8080:8080", "7077:7077"]
    command: ["/opt/spark/sbin/start-master.sh"]
    volumes:
      - ./data/spark-warehouse:/opt/spark/spark-warehouse
      - ./data/examples:/examples

  spark-connect:
    <<: *spark-base
    container_name: spark-connect
    ports: ["15002:15002", "7078:7078", "7079:7079"]
    depends_on: ["spark-master"]
    command: ["/opt/spark/sbin/start-connect-server.sh"]
    volumes:
      - ./data/spark-warehouse:/opt/spark/spark-warehouse
      - ./data/metastore:/opt/spark/metastore
      - ./data/examples:/examples

  spark-worker-1:
    <<: *spark-base
    container_name: spark-worker-1
    depends_on: ["spark-master"]
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    volumes:
      - ./data/spark-warehouse:/opt/spark/spark-warehouse
      - ./data/examples:/examples

  spark-worker-2:
    <<: *spark-base
    container_name: spark-worker-2
    depends_on: ["spark-master"]
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    volumes:
      - ./data/spark-warehouse:/opt/spark/spark-warehouse
      - ./data/examples:/examples

  web:
    build:
      context: ./
      dockerfile: Dockerfile-app
    container_name: web-app
    ports: ["8000:8000", "8888:8888"]
    depends_on: ["spark-connect"]
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./app.py:/app/app.py
      - ./static:/app/static
      - ./templates:/app/templates
      - ./jupyter-nb:/home/jupyter/work
      - ./data/examples:/examples
