spark.master                                           spark://spark-master:7077
spark.driver.host                                      spark-connect
spark.driver.port                                      7078
spark.blockManager.port                                7079
spark.connect.grpc.binding.port                        15002
spark.driver.bindAddress                               0.0.0.0

spark.jars.packages                                    io.delta:delta-spark_2.13:4.0.1
spark.sql.extensions                                   io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog                        org.apache.spark.sql.delta.catalog.DeltaCatalog

spark.sql.catalogImplementation                        hive
spark.sql.warehouse.dir                                file:///opt/spark/spark-warehouse
spark.driver.extraJavaOptions                          -Dderby.system.home=/opt/spark/metastore -Dderby.stream.error.file=/opt/spark/metastore/derby.log
spark.hadoop.javax.jdo.option.ConnectionURL            jdbc:derby:;databaseName=/opt/spark/metastore/metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName     org.apache.derby.jdbc.EmbeddedDriver

spark.sql.sources.default                              delta
spark.databricks.delta.retentionDurationCheck.enabled  false
